[package]
name = "liquidity-pool-meta"

version = "0.0.0"
authors = [ "you",]
edition = "2018"
publish = false

[dependencies.liquidity-pool]
path = ".."

[dependencies.elrond-wasm]
version = "0.30.0"

[dependencies.elrond-wasm-debug]
version = "0.30.0"
