[package]
name = "liquidity_pool"
version = "0.0.1"
authors = [ "you",]
edition = "2018"
publish = false

[lib]
path = "src/lib.rs"

[features]
wasm-output-mode = [ 
    "elrond-wasm-node", 
    "price-aggregator-proxy/wasm-output-mode",
]

[dependencies.elrond-wasm]
version = "0.20"
features = ["derive"]

[dependencies.elrond-wasm-node]
version = "0.20"
optional = true

[dev-dependencies.elrond-wasm-debug]
version = "0.20"

[dependencies.elrond-wasm-output]
version = "0.20"
features = ["wasm-output-mode", "panic-message"]

[dependencies.common_structs]
path = "../common/structs"

[dependencies.common_checks]
path = "../common/checks"

[dependencies.price-aggregator-proxy]
git = "https://github.com/ElrondNetwork/sc-chainlink-rs"
rev = "8817a46"
