[workspace]
members = [
    "liquidity_pool",
    "liquidity_pool/abi",
    "lending_pool",
    "lending_pool/abi",
    "safety_module",
    "safety_module/abi",
    "common/structs",
    "common/modules/price_oracle",
]
