[package]
name = "common-structs"
version = "0.0.0"
authors = [ "catalin-neagu <catalin.neagu@elrond.com>",]
edition = "2018"

[lib]
path = "src/model.rs"

[dependencies.elrond-wasm]
version = "0.34.1"
