[package]
name = "lending_pool-abi"

version = "0.0.0"
authors = [ "you",]
edition = "2018"
publish = false

[dependencies.lending_pool]
path = ".."

[dependencies.elrond-wasm]
version = "0.20"

[dependencies.elrond-wasm-debug]
version = "0.20"
