[package]
name = "safety-module-meta"
version = "0.0.0"
authors = ["CostinCarabas <costin.carabas@multiversx.com>"]
edition = "2018"
publish = false
[dependencies.safety-module]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.41.0"
