[package]
name = "common_checks"
version = "0.0.0"
authors = [ "",]
edition = "2018"

[lib]
path = "src/checks.rs"

[dependencies.elrond-wasm]
version = "0.21.2"

[dependencies.elrond-wasm-derive]
version = "0.21.2"
